Added dynamic range functionality
DLStahl/CapstoneRemodel pull request #29
Opened 2021-03-30 22:06 UTC by Spensenaz

2021-03-31 01:45 UTC, mmferguson commented on laravel/app/Console/Commands/PushSchedule.php
> +        $row_number = count($all_assns);
Not sure if this should be count($all_assns) +1 because the first row in the file is headers for the columns - line 169.

2021-03-31 23:36 UTC, cj81499 requested changes

2021-04-05 00:20 UTC, mmferguson approved these changes

2021-04-05 02:05 UTC, cj81499 requested changes

2021-04-06 12:56 UTC, cj81499 approved these changes

2021-04-06 21:51 UTC, merged